const data = {
	cuisine_name_en: 'EN cuisine_name_en',
	cuisine_name_ar: 'AR cuisine_name_ar',
	cuisine_name_fr: 'FR cuisine_name_fr',
	main_category_name_en: 'EN category_name_en',
	main_category_name_ar: 'AR category_name_ar',
	main_category_name_fr: 'FR category_name_fr',
	data: {
		cuisine_name_en: 'EN cuisine_name_en',
		cuisine_name_ar: 'AR cuisine_name_ar',
		cuisine_name_fr: 'FR cuisine_name_fr',
		main_category_name_en: 'EN category_name_en',
		main_category_name_ar: 'AR category_name_ar',
		main_category_name_fr: 'FR category_name_fr',
		data: {
			cuisine_name_en: 'EN cuisine_name_en',
			cuisine_name_ar: 'AR cuisine_name_ar',
			cuisine_name_fr: 'FR cuisine_name_fr',
			main_category_name_en: 'EN category_name_en',
			main_category_name_ar: 'AR category_name_ar',
			main_category_name_fr: 'FR category_name_fr',
			data: {
				cuisine_name_en: 'EN cuisine_name_en',
				cuisine_name_ar: 'AR cuisine_name_ar',
				cuisine_name_fr: 'FR cuisine_name_fr',
				main_category_name_en: 'EN category_name_en',
				main_category_name_ar: 'AR category_name_ar',
				main_category_name_fr: 'FR category_name_fr',
				data: {
					cuisine_name_en: 'EN cuisine_name_en',
					cuisine_name_ar: 'AR cuisine_name_ar',
					cuisine_name_fr: 'FR cuisine_name_fr',
					main_category_name_en: 'EN category_name_en',
					main_category_name_ar: 'AR category_name_ar',
					main_category_name_fr: 'FR category_name_fr',
				},
			},
		},
	},
};
